### ISSUE TITLE
Create a simple test file

### ISSUE THREAD

**Issue by antoninklopp** [Shahabks/myprosody#4]
Hi @Shahabks , 

Thanks for this project that seems to be exactly what I am looking for! 
However, some things are not working like the **mysplev** function because of missing 
``` python
import pickle
```
which means it could not run anytime. 

Moreover, I fail to use the project with the sample file given in the my prosody folder or with any other file I recorded. It always fails at some point. 

Therefore I have two requests : 

- Could you please provide a test script with all or part of the features? 
- Could you write clearer error logs when the program fails? 

Thank you very much ! 

Antonin

**Comment by antoninklopp** [comment]
The functions that never work for me are  : **myprosody** and **mysplev**

**Comment by Shahabks** [comment]
Hello Antonin,
You are most welcome. I hope the library works for you after our discussion
here.
You need to install pickle if you wish to use "SpeechRater" or evaluating
spoken language prosody, pronunciation, structures of an audio
file.......It is because those some functions, such as "mysplev", were
developed based on machine learning algorithms.

the function "mysplev" does not work for you either

   1. you have not installed the pickle library on your virtual environment
   2. your machine is not compatible with the version of ML algorithm that
   I developed.......In this case you need to train the ML models (Acoustic
   and language models) on your machine (my previous experience with another
   user of Myprosody)
   3. if you download or clone
   https://github.com/Shahabks/myprosody/tree/master/myprosody/dataset from
   my github, please remember to follow these steps


   -  unzipped the downloaded directory
   - extract the directory inside (copy and paste) on your desktop or
   wherever you wish on your machine.
   - THE PATH to the DIRECTORY SHOULD BE "  / wherever you save
/myprosody /......for
   example (c:/users/your name/desktop/myprosody/
   - IN THE directory MYPROSODY you should have now  / -------- /myprosody /
   dataset/audioFiles/ where you save your audio files ............ for
   example (c:/users/your name/desktop/myprosody/ dataset/audioFiles/
   - IN THE directory MYPROSODY you should have now   / -------- /myprosody
   /dataset/ essen/ where you save all models already available in essen
   folder from my Github

Please let me know if you run again in any issue
Kind regards
Shahab

**Comment by antoninklopp** [comment]
I actually found my issue. 
It was because I don't have any pauses in my file, and this was making a division by zero error in the praat script. 

What I meant by making a test file, is just creating a **test.py** that someone can simply run to see how the project works and create it himself. 

Thanks, 
Antonin

**Comment by Shahabks** [comment]
Cool....sure I will add it right now

**Comment by Shahabks** [comment]
i did it

**Comment by antoninklopp** [comment]
Thanks!
